# Claude工作流配置

version: "1.0"
project_type: "rust"

# 开发工作流
workflow:
  - name: "代码检查"
    description: "检查代码质量和格式"
    commands:
      - "cargo check"
      - "cargo clippy"
      - "cargo fmt --check"
  
  - name: "运行测试"
    description: "执行所有测试"
    commands:
      - "cargo test --lib"
  
  - name: "构建项目"
    description: "构建优化版本"
    commands:
      - "cargo build --release"
  
  - name: "性能验证"
    description: "验证构建结果"
    commands:
      - "./target/release/img-squeeze --help"
      - "./target/release/img-squeeze --version"

# 快捷命令
aliases:
  dev: "cargo check && cargo clippy"
  test: "cargo test --lib"
  build: "cargo build --release"
  clean: "cargo clean"