[package]
name = "img-squeeze"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = { version = "0.25", features = ["jpeg", "png", "webp"] }
anyhow = "1.0"
indicatif = "0.17"
